version: "3.9"

services:
  nessie:
    image: projectnessie/nessie:latest
    container_name: catalog
    networks:
      - air_quality_net
    ports:
      - "19120:19120"
    environment:
      nessie.catalog.default-warehouse: lakehouse
      nessie.catalog.warehouses.lakehouse.location: s3://lakehouse

      nessie.catalog.service.s3.default-options.endpoint: http://minio:9000
      nessie.catalog.service.s3.default-options.path-style-access: true
      nessie.catalog.service.s3.default-options.region: us-east-1
      nessie.catalog.service.s3.default-options.access-key.name: admin
      nessie.catalog.service.s3.default-options.access-key.secret: password

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: storage
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
    networks:
      - air_quality_net
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio-init:
    image: minio/mc:latest
    container_name: minio_init
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - air_quality_net
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 admin password &&
      mc mb local/raw || true &&
      mc mb local/bronze || true &&
      mc mb local/silver || true &&
      mc mb local/gold || true &&
      echo 'MinIO buckets are ready.'
      "

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    container_name: dremio
    environment:
      DREMIO_JAVA_SERVER_EXTRA_OPTS: -Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      - air_quality_net
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"
    volumes:
      - dremio_data:/opt/dremio/data

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - air_quality_net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  airflow:
    image: apache/airflow:3.0.1-python3.11
    container_name: airflow
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    command: standalone
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:password@postgres:5432/airflow_meta
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      _AIRFLOW_WWW_USER_FIRSTNAME: Airflow
      _AIRFLOW_WWW_USER_LASTNAME: Admin
      _AIRFLOW_WWW_USER_ROLE: Admin
      _AIRFLOW_WWW_USER_EMAIL: admin@example.com
    networks:
      - air_quality_net
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

networks:
  air_quality_net:

volumes:
  minio_data:
  dremio_data:
  postgres_data: